server:
  port: 9191

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  application:
#    name: CATALOG-SERVICE

logging:
  file:
    name: C:/Users/user/Desktop/Logs/microservices/logfile.log