server:
  port: 9000

spring:
  application:
    name: API-GATEWAY
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/fallBack
#        - id: CATALOG-SERVICE
#          uri: lb://CATALOG-SERVICE
#          predicates:
#              - Path=/orders/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: CATALOG-SERVICE
#                fallbackuri: forward:/fallBackForCatalog

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8761/eureka"
  instance:
    hostname: localhost

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always